### ISSUE TITLE
Create GET request by ID for albums

### ISSUE THREAD

**Issue by Mahik99** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-syntax_squad#10]
```[tasklist]
### Tasks
- [ ] Write the function to get an albums by its ID in album.js file
- [ ] if there is a matching ID for album then return that album else throw an error
- [ ] Create the get album by ID request in app.js file
```
