### ISSUE TITLE
Create an UpdateAlbumById request

### ISSUE THREAD

**Issue by Mahik99** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-syntax_squad#12]
```[tasklist]
### Tasks
- [ ] Write the function to update album by ID in album.js file
- [ ] if there is a matching ID for album then update that album with the new album, else throw an error
- [ ] Create the PATCH request to update album by ID request in app.js file
- [ ] Test that it works through Postman and returns new album
```
