### ISSUE TITLE
basic set up

### ISSUE THREAD

**Issue by Mahik99** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-syntax_squad#2]
```[tasklist]
### Tasks
- [x] Clone Repo
- [x] Run npm install command
- [x] Create a database on render (Postgres)
- [x] Add connection string and port number to env file (remove .example from file name)
```
