### ISSUE TITLE
Database preparation

### ISSUE THREAD

**Issue by Mahik99** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-syntax_squad#3]
```[tasklist]
### Tasks
- [ ] Update file names and varaible names/requests to artist/albums (resource one: artists, resource two: albums)
- [ ] run reset-database command
- [ ] run npm dev
- [ ] Test server connection via postman (console.log im alive)
```
