### ISSUE TITLE
Create Get request for artists

### ISSUE THREAD

**Issue by Mahik99** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-syntax_squad#4]
```[tasklist]
### Tasks
- [x] Write the function to get list of artists in artist.js file
- [x] Modify the app.get request to retrieve a list of the artists in app.js file
- [ ] Test that the get request works in postman
```
