### ISSUE TITLE
Create a Post request

### ISSUE THREAD

**Issue by Mahik99** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-syntax_squad#5]
```[tasklist]
### Tasks
- [ ] Write the function to create a new artist in artist.js file
- [ ] Create a Post request in app.js to return the newly created artist
- [ ] Test that the POST request works in postman
```
