### ISSUE TITLE
Create a GET request by ID

### ISSUE THREAD

**Issue by Mahik99** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-syntax_squad#6]
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] Write the function to get artist by ID in artist.js file
- [ ] if there is a matching ID for artist then return that artist else throw an error
- [ ] Create the get artist by ID request in app.js file
```
