### ISSUE TITLE
Create an updateArtistById request

### ISSUE THREAD

**Issue by Mahik99** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-syntax_squad#7]
```[tasklist]
### Tasks
- [ ] Write the function to update artist by ID in artist.js file
- [ ] if there is a matching ID for artist then update that artist with the new artist, else throw an error
- [ ] Create the PATCH request to update artist by ID request in app.js file
- [ ] Test that it works through Postman
```
