### ISSUE TITLE
Create deleteArtistById request

### ISSUE THREAD

**Issue by Mahik99** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-syntax_squad#8]
```[tasklist]
### Tasks
- [ ] Write the function to delete artist by ID in artist.js file
- [ ] if there is a matching ID for artist then delete that artist, else throw an error
- [ ] Create the DELETE request to delete artist by ID request in app.js file
- [ ] Test that it works through Postman
```
