### ISSUE TITLE
Create GET request for albums

### ISSUE THREAD

**Issue by Mahik99** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-syntax_squad#9]
```[tasklist]
### Tasks
- [x] Write the function to get list of albums in album.js file
- [x] Modify the app.get request to retrieve a list of the artists in app.js file
- [x] Test that the get request works in postman
```
